from pathlib import Path
p=Path('dist/index.html');s=p.read_text()
s=s.replace('<div class="view-buttons">','<div class="view-buttons" role="group" aria-label="Camera view">').replace('class="selected" id="orbit"','class="selected" id="orbit" aria-pressed="true"').replace('id="follow">','id="follow" aria-pressed="false">')
s=s.replace('id="viewport" aria-label="3D rally track and neural drivers"','id="viewport" tabindex="0" role="region" aria-label="3D rally circuit. Arrow keys rotate the overview; plus and minus zoom." aria-describedby="camera-help"')
s=s.replace('<div class="scene-help">Drag to orbit <span>·</span> Scroll to zoom</div>','<div class="scene-help" id="camera-help">Drag / arrows to orbit <span>·</span> Scroll / + − to zoom</div>')
s=s.replace('<div class="progress"><span id="progress-bar"></span></div>','<div class="progress" id="lap-progress" role="progressbar" aria-label="Leading lap progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span id="progress-bar"></span></div>')
s=s.replace('<button id="export" disabled>↓ Export driver</button>','<button id="export" disabled>↓ Export driver</button><button id="share" disabled>↗ Copy driver link</button>')
s=s.replace('<div class="legend">','<div class="legend">')
s=s.replace('<div class="bottom-grid">','''<div id="runtime-error" class="error-banner" role="alert" hidden><span id="runtime-message"></span><button id="retry-render">Retry view</button></div>
<section class="line-toolbar" aria-label="Racing line controls"><label><input id="show-lines" type="checkbox" checked> Show learned racing lines</label><span id="line-summary">A completed champion lap will draw the first line.</span><span class="line-key"><i></i> 0 → 120 km/h · earlier improvements fade</span></section>
<div class="bottom-grid">''')
s=s.replace('<footer><span>RALLY', '''<section class="data-panel comparison-panel"><div class="section-heading"><div><h2>Algorithm comparison</h2><p class="muted">Same track, same initial population, same 48 evaluations per generation.</p></div><div class="comparison-controls"><label for="comparison-budget">Budget</label><select id="comparison-budget"><option value="20">20 generations</option><option value="50">50 generations</option><option value="100">100 generations</option></select><button id="compare" class="secondary">Run comparison</button></div></div>
<div class="comparison-chart"><canvas id="comparison-chart" role="img" aria-label="Best lap time by evaluated drivers for three search algorithms"></canvas><p id="comparison-empty">Compare genetic search, hill climbing and random search on this circuit.</p></div>
<div class="comparison-legend"><span><i style="background:#d6fa59"></i> Genetic search</span><span><i style="background:#67c5ee"></i> Hill climber</span><span><i style="background:#cf9bf5"></i> Random search</span><span>Lower lap time is better</span></div>
<table class="comparison-results"><caption id="comparison-status">No comparison run yet. Runs independently of your live session.</caption><thead><tr><th scope="col">Algorithm</th><th scope="col">Evaluations</th><th scope="col">Best lap</th><th scope="col">Best progress</th></tr></thead><tbody id="comparison-results"><tr><th scope="row">Genetic search</th><td>0</td><td>—</td><td>—</td></tr><tr><th scope="row">Hill climber</th><td>0</td><td>—</td><td>—</td></tr><tr><th scope="row">Random search</th><td>0</td><td>—</td><td>—</td></tr></tbody></table></section>
<footer><span>RALLY''')
s=s.replace('id="status">','id="status" role="status">')
s=s.replace('id="chart" aria-label=','id="chart" role="img" aria-label=').replace('id="profile" aria-label=','id="profile" role="img" aria-label=')
s=s.replace('id="laps-count">','id="laps-count" aria-live="polite">')
s=s.replace('<dialog id="about-dialog">','<dialog id="about-dialog" aria-labelledby="about-title">').replace('<h2>Learning, one lap at a time.</h2>','<h2 id="about-title">Learning, one lap at a time.</h2>')
s=s.replace('Export saves its weights and track settings.', 'Export or copy a driver link to save its exact weights and track settings. Links evaluate the driver locally before showing a lap time. The racing line shows up to four improved champion laps, colored by speed. Algorithm comparison gives each method the same evaluation budget; results describe this one track and random seed, not a universal winner.')
s=s.replace('After each generation, the best drivers survive; their weights are combined and mutated to create the next population.', 'After each generation, the best drivers survive; their weights are combined and mutated to create the next population. After 25 generations without improvement, mutation increases and fresh drivers enter while the champion survives.')
s=s.replace('</body>','<dialog id="link-dialog" aria-labelledby="link-title"><div class="dialog-top"><h2 id="link-title">Your driver link</h2><button id="close-link" aria-label="Close driver link">✕</button></div><p>Copy this URL to share or save the driver. The recipient needs access to the app. A localhost link works only where this project is running.</p><label for="driver-link">Full link</label><input id="driver-link" readonly><button id="copy-link" class="primary">Copy link</button></dialog></body>')
p.write_text(s)
p=Path('dist/style.css');s=p.read_text();s+='''
/* Pace notes: preserve the circuit's visual identity; improve controls and legibility. */
[hidden]{display:none!important}.error-banner{display:flex;align-items:center;justify-content:space-between;gap:16px;border:1px solid #b37663;background:#472d25;padding:16px;margin-top:16px;font-size:16px}.error-banner button{border:1px solid currentColor;padding:8px 12px;flex-shrink:0}
.line-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:12px 22px;padding:18px 0 0;font-size:14px;color:#b8c4af}.line-toolbar label{color:#e4edda;display:flex;align-items:center;gap:9px}.line-toolbar input{accent-color:var(--acid);width:18px;height:18px}.line-key{display:flex;align-items:center;gap:8px;font-size:12px}.line-key i{display:inline-block;width:60px;height:4px;background:linear-gradient(90deg,#67c5ee,#d6fa59)}
.session-actions{flex-wrap:wrap;gap:14px}.session-actions button{font-size:14px;min-height:30px}.control-row,.range-label,.completion-label,.quiet,.view-buttons button{font-size:14px}.muted,.fine,.track-stats,.range-ends,.scene-help,.legend,.simulation-footer,.terrain-note,.data-panel .section-heading>span{font-size:12px}.control-row select{font-size:12px}input[type=range]{height:20px}.scene-help{background:#18231599;padding:5px 7px;top:20px}.chart-caption{font-size:12px;gap:15px}.chart-y{font-size:12px;width:48px}.chart-caption>span:first-child{font-family:var(--body)}.speed-hud>span,.input-meter label,.speed-hud small{font-size:11px}.input-meter label{width:65px}.speed-hud{width:155px}.world-label small{font-size:12px}.scene-top{font-size:12px}#viewport:focus-visible{outline:2px solid var(--acid);outline-offset:-3px}.profile-labels{font-size:12px}
.comparison-panel{margin-top:20px}.comparison-panel .section-heading{align-items:start}.comparison-panel .muted{margin-bottom:0;font-size:14px}.comparison-controls{display:flex;align-items:center;gap:12px;font-size:14px}.comparison-controls .secondary{width:auto;white-space:nowrap;padding:0 18px}.comparison-controls select{max-width:none;font-size:13px}.comparison-chart{position:relative;height:200px;margin-top:20px}.comparison-chart canvas{width:100%;height:100%}#comparison-empty{position:absolute;inset:0;display:grid;place-content:center;text-align:center;font-size:15px;color:var(--muted);padding:20px;pointer-events:none}.comparison-legend{display:flex;flex-wrap:wrap;gap:12px 24px;margin:15px 0;font-size:14px}.comparison-legend i{display:inline-block;width:9px;height:9px;margin-right:6px}.comparison-legend>span:last-child{margin-left:auto;color:var(--muted)}.comparison-results{width:100%;border-collapse:collapse;font-size:14px;text-align:left}.comparison-results th,.comparison-results td{padding:10px 12px;border-top:1px solid var(--line)}.comparison-results thead{color:var(--muted)}.comparison-results td{font-family:var(--mono);font-size:13px}.comparison-results caption{text-align:left;margin:12px 0;color:var(--muted);font-size:14px}#driver-link{width:100%;padding:12px;margin:12px 0 20px;background:#111812;border:1px solid var(--line);color:var(--text);font-size:14px}
@media(max-width:1100px){.comparison-panel .section-heading{flex-direction:column;gap:18px}.comparison-controls{flex-wrap:wrap}}@media(max-width:760px){.scene-help{display:none}.chart-caption{flex-wrap:wrap}.scene-top{font-size:10px}.simulation-footer{font-size:10px}.comparison-results th,.comparison-results td{padding:10px 4px}.comparison-results td{font-size:12px}.comparison-legend>span:last-child{margin-left:0}.line-toolbar{font-size:14px}.stats strong{font-size:34px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
''';p.write_text(s)
