const $=id=>document.getElementById(id);let sessions=[],current=null,selected=null,stream=null,rec=null,recording=false,timer=null,elapsed=0,started=0,keyReady=false,pending=0,chain=Promise.resolve(),view='live';
const stamp=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
const now=()=>elapsed+(recording?(Date.now()-started)/1000:0);
const status=t=>$('status').textContent=t;
async function api(path,data){const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const x=await r.json();if(!r.ok)throw Error(x.error||'Could not save');return x}
function safe(fn){return async(...a)=>{try{await fn(...a)}catch(e){status(e.message)}}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000)}
async function refresh(){const x=await api('state');sessions=x.sessions;keyReady=x.keyReady;if(current)current=sessions.find(s=>s.id===current.id);else current=sessions[0]||null;render()}
function render(){ $('sessions').replaceChildren();for(const s of sessions){let b=document.createElement('button');b.textContent=s.title;b.disabled=recording||pending>0;b.onclick=()=>{current=s;selected=null;elapsed=s.elapsed;render()};$('sessions').append(b)}$('title').textContent=current?.title||'Capture the board. Keep the reasoning.';$('clock').textContent=stamp(now());$('new').disabled=recording||pending>0;$('record').textContent=recording?'■ Stop & save':'● Record lecture';$('keystate').textContent=keyReady?'API key available. Enable AI processing to use it.':'No API key configured.';
if(!current)return; $('timeline').replaceChildren();const events=[...current.events].sort((a,b)=>a.time-b.time);for(const e of events){if(view==='live'&&e.type==='explanation')continue;let card=document.createElement('article');card.className='event'+(e.id===selected?' selected':'');card.onclick=()=>{selected=e.id;render()};let meta=document.createElement('div');meta.className='meta';meta.textContent=`${stamp(e.time)}  ·  ${e.type.toUpperCase()}${e.corrected?' · CORRECTED':''}`;card.append(meta);if(e.type==='board'){let img=document.createElement('img');img.src=e.data;img.alt='Class board at '+stamp(e.time);card.append(img)}if(e.type==='audio'){let a=document.createElement('audio');a.controls=true;a.src=e.data;a.onclick=ev=>ev.stopPropagation();card.append(a);let b=document.createElement('button');b.textContent=e.text?'Transcribe again':'Transcribe clip';b.onclick=safe(async ev=>{ev.stopPropagation();requireAI();b.disabled=true;try{status('Transcribing saved audio…');const result=await api('transcribe',{session:current.id,id:e.id});Object.assign(e,result);render();status('Transcript saved. Check names, reagents, and charges against the board.')}finally{b.disabled=false}});card.append(b)}if(e.text){let p=document.createElement('p');p.textContent=e.text;card.append(p)}if(e.type!=='explanation'){let edit=document.createElement('button');edit.textContent=e.type==='audio'?'Correct / add transcript':'Annotate';edit.onclick=ev=>{ev.stopPropagation();if(card.querySelector('textarea'))return;let t=document.createElement('textarea');t.value=e.text||'';t.onclick=ev=>ev.stopPropagation();let save=document.createElement('button');save.textContent='Save';save.onclick=safe(async ev=>{ev.stopPropagation();Object.assign(e,await api('edit',{session:current.id,id:e.id,text:t.value}));render()});card.append(t,save);t.focus()};card.append(edit)}$('timeline').append(card)}if(!events.length){let p=document.createElement('div');p.className='empty';p.textContent='Ready for class. Record audio, add a board photo, or write a note.';$('timeline').append(p)}}
function requireSession(){if(!current)throw Error('Create a lecture first.')}
function requireAI(){if(!$('cloud').checked)throw Error('Enable AI processing in the explanation panel first.');if(!keyReady){$('settings').showModal();throw Error('Add an API key to use AI. Your captured class is saved locally.')}}
async function add(event,sid=current?.id){if(!sid)throw Error('Create a lecture first.');const e=await api('event',{session:sid,event});const s=sessions.find(s=>s.id===sid);s.events.push(e);s.elapsed=Math.max(s.elapsed,e.time);if(current.id===sid)render();return e}
$('new').onclick=()=>{$('lecturetitle').value=`Ochem 2 · ${new Date().toLocaleDateString()}`;$('newlecture').showModal()};
$('cancellecture').onclick=()=>$('newlecture').close();
$('createlecture').onclick=safe(async()=>{const title=$('lecturetitle').value.trim();if(!title)return;current=await api('new',{title,created:new Date().toISOString()});sessions.unshift(current);elapsed=0;selected=null;render();$('newlecture').close();status('Ready. Keep the tab open while recording.')});
const dataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)});
function segment(){const sid=current.id;const t=now();const mime=['audio/webm;codecs=opus','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));rec=new MediaRecorder(stream,mime?{mimeType:mime}:{});const parts=[];rec.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};rec.onerror=e=>status('Microphone recording error. Stop and check the saved clips.');rec.onstop=()=>{clearTimeout(timer);const blob=new Blob(parts,{type:rec.mimeType});const duration=now()-t;pending++;chain=chain.then(async()=>{try{const data=await dataURL(blob);const e=await add({type:'audio',time:t,duration,data,text:''},sid);if($('cloud').checked&&keyReady){try{const out=await api('transcribe',{session:sid,id:e.id});Object.assign(e,out);render()}catch(err){status('Audio saved. Transcription failed: '+err.message)}}else status('Audio saved locally. Enable AI to transcribe, or add a transcript manually.')}catch(err){download(blob,`unsaved-lecture-${stamp(t).replace(':','-')}.webm`);status('Saving failed. A backup audio download was started: '+err.message)}finally{pending--;render()}});if(recording)segment()};rec.start();timer=setTimeout(()=>{if(rec.state==='recording')rec.stop()},30000)}
$('record').onclick=safe(async()=>{requireSession();if(recording){const t=now();recording=false;elapsed=t;clearTimeout(timer);if(rec?.state==='recording')rec.stop();stream.getTracks().forEach(t=>t.stop());status('Saving final clip…');render();return}if(!navigator.mediaDevices?.getUserMedia)throw Error('Open this app in Chrome or Safari on your laptop to record.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false},video:false});elapsed=Math.max(elapsed,current.elapsed);started=Date.now();recording=true;segment();render();status('Recording. Audio saves in approximately 30-second clips. Keep this tab open.')});
setInterval(()=>{$('clock').textContent=stamp(now())},500);
window.addEventListener('beforeunload',e=>{if(recording||pending){e.preventDefault();e.returnValue='Recording or saving is still in progress.'}});
$('board').onclick=safe(()=>{requireSession();$('file').click()});$('file').onchange=safe(async()=>{requireSession();const file=$('file').files[0];if(!file)return;if(file.size>15e6)throw Error('Choose a photo smaller than 15 MB.');const time=now();const entered=$('boardtime').value.trim()||stamp(time);if(!/^\d+:\d{2}$/.test(entered)||Number(entered.split(':')[1])>59)throw Error('Use a timestamp like 12:30.');const [m,s]=entered.split(':').map(Number);const e=await add({type:'board',time:m*60+s,data:await dataURL(file),text:''});selected=e.id;render();$('file').value='';status('Board saved. Select Annotate to identify unclear reagents or bonds.')});
for(const [id,label] of [['confused','Confusing — revisit this step'],['important','Important — user bookmark']])$(id).onclick=safe(async()=>{requireSession();await add({type:'bookmark',time:now(),text:label});status('Moment bookmarked.')});
$('noteform').onsubmit=safe(async e=>{e.preventDefault();requireSession();if(!$('note').value.trim())return;await add({type:'note',time:now(),text:$('note').value});$('note').value='';status('Note saved.')});
async function explain(mode){requireSession();requireAI();const question=$('question').value;if(mode==='question'&&!question.trim())throw Error('Type a question first.');if(mode==='mechanism'&&!current.events.some(e=>e.type==='board'))throw Error('Add a board photo first.');$('answer').textContent='Working from your class evidence…';document.querySelectorAll('[data-mode],#ask').forEach(b=>b.disabled=true);try{const e=await api('explain',{session:current.id,selected,mode,question});current.events.push(e);$('answer').textContent=e.text;render();status('Explanation saved. Verify the structure against your board photo.')}catch(e){$('answer').textContent=e.message;throw e}finally{document.querySelectorAll('[data-mode],#ask').forEach(b=>b.disabled=false)}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=safe(()=>explain(b.dataset.mode)));$('ask').onclick=safe(()=>explain('question'));
for(const id of ['live','study'])$(id).onclick=()=>{view=id;$(id).classList.add('active');$(id==='live'?'study':'live').classList.remove('active');$('tutor-title').textContent=id==='study'?'Turn this class into practice.':'Stay with the mechanism.';render()};
$('setup').onclick=()=>$('settings').showModal();$('close').onclick=()=>$('settings').close();$('savekey').onclick=safe(async()=>{const x=await api('key',{key:$('key').value});keyReady=x.keyReady;$('key').value='';render();$('settings').close();status('AI key updated. Enable AI processing when ready.')});
$('export').onclick=safe(()=>{requireSession();download(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),current.title.replace(/[^a-z0-9]/gi,'-')+'.json');const text=[current.title,...[...current.events].sort((a,b)=>a.time-b.time).map(e=>`[${stamp(e.time)}] ${e.type}\n${e.text||'(Media saved in JSON notebook)'}`)].join('\n\n');download(new Blob([text],{type:'text/plain'}),'lecture-notes.txt');status('Exported notes and a complete notebook containing audio and photos.')});
refresh().then(()=>{if(current){elapsed=current.elapsed;render();status('Saved lecture restored. Recording is stopped.')}}).catch(e=>status('Unable to load saved lectures: '+e.message));
