"""Report completed bounded model/interface investigations honestly."""
import sys,json,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from flygarden.recording import atomic_json
from flygarden.continuous_candidate import file_sha
BASE=ROOT/'reports/brain-integration/recovery'
def main():
 ref=json.loads((BASE/'persistence-reference-v1/results.json').read_text());mb=json.loads((BASE/'mbon32-capability-v1/results.json').read_text());scale=json.loads((BASE/'synaptic-scale-calibration-v1/calibration-decision.json').read_text());assert ref['status']=='passed' and mb['status']=='audits_passed'
 manifests=[]
 for folder in ('persistence-reference-v1','mbon32-capability-v1','synaptic-scale-calibration-v1'):
  manifests += list((BASE/folder).glob('*/manifest.json'))+list((BASE/folder).glob('diagnostics/*/manifest.json'))
 stats=[json.loads(p.read_text()) for p in manifests];assert len(stats)==40 and all(m['status']=='complete' for m in stats)
 wall=sum(m['wall_seconds'] for m in stats);peak=max(m['peak_rss_bytes'] for m in stats)/1024**3
 lines=['# Neural model/interface review','','## Completed work','','40 new full-network trials: eight extended reference/candidate simulations, eight direct MBON32 capability diagnostics and 24 prospectively registered global-strength variants. All source/data identities and raw-event/count/decoder audits pass. Learning is off; the application and original imported network are unchanged.','','## Extended reference comparison','','Four matched pairs, two disjoint seeds and support0/65Hz, run4 simulated seconds with odorA5Hz/root only during.3–.8s. All160 windows per pair match individual spike IDs/times/counts and input events exactly; selected voltage/g match within the prior1e-10mV absolute tolerance. Shared external-event construction replaces native PoissonInput and the redundant original reset w=0 is omitted as in the previous equation replay. This is a bounded equation-level reference comparison, not published behavior or full native-stochastic equivalence.','','| Seed | Support Hz | Final .5s DNa02 L/R Hz | Final .5s DM1 PN L/R Hz |','|---:|---:|---:|---:|']
 for r in ref['pairs']:
  p=r['phase_rates_hz']['late_recovery'];lines.append(f"| {r['seed']} | {r['support']} | {p['DNa02_left']:.1f}/{p['DNa02_right']:.1f} | {p['DM1_lPN_left']:.1f}/{p['DM1_lPN_right']:.1f} |")
 lines+=['','Stimulated DM1 ORNs are quiet in the final .5s, yet downstream activity persists. Some unstimulated DM2 ORNs show low recurrent activity; do not claim all receptors are silent. Persistence is reproduced by independent released-equation construction under these inputs, so an adapter-only explanation is unsupported for these cases. This does not prove every integration component correct or identify a unique biological cause.','','![Verified persistent activity](persistence-reference-v1/persistent-activity.png)','','## Downstream pathway capability','','The literature proposes MBON32 participation in learned appetitive/aversive steering and supports the bilateral DNa02 difference readout: [Rayshubskiy et al.](https://elifesciences.org/articles/102230). It does not validate a uniform DM1/DM2-to-ipsilateral-turn transformation in this generic model. Exact MBON32 roots were directly stimulated at50Hz with matched65Hz support. These are capability tests, not sensory inputs or navigation.','','| Seed | Pulse change L cue / R cue / both (Hz) | Recovery gate | Directional capability |','|---:|---:|---|---|']
 for r in mb['gates']:
  p=r['pulse_difference_hz'];lines.append(f"| {r['seed']} | {p['left']:.1f}/{p['right']:.1f}/{p['both']:.1f} | {r['gates']['recovery']} | {r['passed']} |")
 lines+=['','Direct MBON32 does not provide the registered mirrored response under these conditions. This does not prove MBON32 has no role in natural behavior. Preserved effective-delivery diagnostics implicate inhibition in right-DNa02 suppression, while the new anatomical/presynaptic tail rankings are hypotheses only. No inhibitory lesion or sensory-to-motor bypass is installed.','','## Explicit model parameter variants','','[Shiu et al.](https://www.nature.com/articles/s41586-024-07763-9) tested global synaptic strength±30% for robustness of their specific predictions. We prospectively test0.7/1/1.3 strength with no odor/left/right/bilateral stimuli on seeds10301/10302. All neuron/connection counts and signs are retained; full weight fingerprints remain fixed during trials. These are altered model parameters, not original-model equivalence. Decoder/support stay fixed.','','The global-strength capability gate '+('passes for a candidate, which needs a separately registered physical evaluation before any promotion.' if scale['status']=='passed' else 'fails for every tested strength. No candidate is frozen or promoted; held-out physical navigation is not started.'),'','See [parameter results](synaptic-scale-calibration-v1/RESULTS.md) for every gate and retained failure.','','## Decision','','Stop unstructured odor-gain and global-strength sweeps. The next justified research phase is a source-backed neural-dynamics/operating-state revision with an independently validated reference case, followed by the same direction/recovery gates. Candidate mechanisms such as heterogeneous intrinsic dynamics, receptor-specific responses or adaptation must be supported and tested, not invented to force steering. A revision must get a new model identity and clearly list all differences. Preserve the released model as a reference and keep full-network coverage; no reduced network substitution. Navigation, biological fidelity and learning remain unvalidated.','','The parent garden plan remains active. This package resolves a narrower question about tested persistence and interface capability; it does not complete the application, research or delivery acceptance.','','## Runtime','',f'Trial timers total {wall:.1f} wall seconds; peak trial worker RSS {peak:.2f} GiB. Excludes startup outside timers, read-only audits and plotting. Raw recordings retained.','']
 path=BASE/'MODEL_INTERFACE_REVIEW.md';path.write_text('\n'.join(lines))
 atomic_json(BASE/'model-interface-review.json',{'status':'bounded_review_complete','trials':40,'reference_passed':True,'mbon32_capability_passed':mb['capability_gate_passed'],'parameter_capability_passed':scale['status']=='passed','navigation_validated':False,'learning_validated':False,'production_controller_changed':False,'wall_seconds_trial_sum':wall,'peak_worker_rss_gib':peak,'evidence':{str(p.relative_to(ROOT)):file_sha(p) for p in [path,BASE/'persistence-reference-v1/results.json',BASE/'mbon32-capability-v1/results.json',BASE/'synaptic-scale-calibration-v1/calibration-decision.json']}})
 print('Review retained:',len(stats),'completed full-network trials')
if __name__=='__main__':main()
