from pathlib import Path
import pandas as pd,json
root=Path(__file__).resolve().parents[1];ann=pd.read_csv(root/'data/annotations.tsv',sep='\t',low_memory=False).fillna('');ids=set(pd.read_csv(root/'vendor/fly-brain/data/2025_Completeness_783.csv',index_col=0).index);ann=ann[ann.root_id.isin(ids)]
pop={}
for name,type_ in [('odor_a','ORN_DM1'),('odor_b','ORN_DM2'),('p9','DNp09'),('reward_mbon','MBON01'),('aversive_mbon','MBON11'),('reward_dan','PAM01'),('aversive_dan','PPL101'),('looming','LPLC2')]:
 d=ann[ann.cell_type==type_];pop[name]=dict(cell_type=type_,neurons=[dict(root_id=str(r.root_id),side=r.side,transmitter=r.top_nt) for r in d.itertuples()])
report=dict(version=1,populations=pop,source='FlyWire annotation table pinned by hash in provenance.json',sensory_encoding='Synthetic independent odor channels stimulate ORN_DM1/DM2; geometric looming proxy stimulates side-matched LPLC2',motor_decoding='Smoothed DNp09 left/right firing rates, /100Hz into supplied leg controller; tonic 65Hz engineered exploration',learning=dict(reward=dict(compartment='gamma5',kc='KCg*',mbon='MBON01',dan='PAM01',update='Activity eligibility followed by depression of excitatory KCg -> MBON01 magnitude'),aversive=dict(compartment='gamma1pedc',kc='KCg*',mbon='MBON11',dan='PPL101',update='Activity eligibility followed by depression of excitatory KCg -> MBON11 magnitude'),learning_rate=.08,eligibility_tau_seconds=2.,weight_bounds_relative=[.1,1.],validation='Engineered rule; not fitted or biologically validated'),sources=['https://elifesciences.org/articles/62576','https://www.nature.com/articles/s41586-024-07819-w','https://www.nature.com/articles/s41467-021-22592-4'],limitations=['No inferred molecular dynamics','KCg -> MBON01 selects gamma contributions, omits beta-prime contributions','PAM01 has subtypes; stimulation groups them without inferred subtype specificity','LPLC2 stimulation is an engineered feature encoding, not retinal pathway simulation','Poisson-driven input populations use zero refractory period as released stimulation convention'])
(root/'reports/neuron-mapping.json').write_text(json.dumps(report,indent=2))
print({k:len(v['neurons']) for k,v in pop.items()})
