/**
 * THROUGHPUT panel — measured environment steps/s vs workers.
 *
 * Renders the B1/B2 benchmark numbers seeded in
 * `public/dashboard/throughput.json`: SyncVecEnv n=1..16, AsyncVecEnv
 * w=1..12, scaling efficiency against ideal linear, and the tracked
 * regression metric (8-worker steps/s). The numbers are regenerated by
 * `python -m rallyai.train.bench`; the control room has no bench endpoint
 * (jobs / live / drive only), so re-running is a copy-paste CLI affair.
 */

import { registerPanel } from "../DashboardApp";
import type { PanelContext } from "../types";

// --- data contract (mirrors public/dashboard/throughput.json) --------------

interface SyncPoint {
  n: number;
  stepsPerS: number;
}

interface AsyncPoint {
  workers: number;
  stepsPerS: number;
}

interface ThroughputDoc {
  meta: {
    source: string;
    host: string;
    conditions: string;
    control: string;
    benchCommand: string;
    scaleCommand: string;
  };
  sync: SyncPoint[];
  async: AsyncPoint[];
  tracked: {
    workers: number;
    stepsPerS: number;
    speedupVsSync1: number;
    note: string;
  };
  waiver: string;
  projection: string;
}

const DATA_URL = `${import.meta.env.BASE_URL}dashboard/throughput.json`;

/** Suggested full re-run: 8-worker bench with the sync/1 comparison baked in. */
const RERUN_CMD =
  "packages/sim/.venv/bin/python -m rallyai.train.bench --workers 8 --steps 20000 --compare-sync1";
const SCALE_CMD = "packages/sim/.venv/bin/python -m rallyai.train._bench_scale";

// --- helpers ----------------------------------------------------------------

function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function fmt(n: number): string {
  return Math.round(n).toLocaleString("en-US");
}

/** Round a chart ceiling up to the next 500 steps/s. */
function niceMax(value: number): number {
  return Math.max(500, Math.ceil((value * 1.08) / 500) * 500);
}

async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

// --- chart ------------------------------------------------------------------

const CHART_W = 760;
const CHART_H = 340;
const PAD = { left: 58, right: 16, top: 20, bottom: 40 } as const;

interface ChartScales {
  x: (workers: number) => number;
  y: (stepsPerS: number) => number;
  yMax: number;
  xMax: number;
}

function makeScales(doc: ThroughputDoc): ChartScales {
  const xMax = Math.max(
    ...doc.sync.map((p) => p.n),
    ...doc.async.map((p) => p.workers),
  );
  const yMax = niceMax(
    Math.max(
      ...doc.sync.map((p) => p.stepsPerS),
      ...doc.async.map((p) => p.stepsPerS),
    ),
  );
  const plotW = CHART_W - PAD.left - PAD.right;
  const plotH = CHART_H - PAD.top - PAD.bottom;
  return {
    x: (w) => PAD.left + (w / xMax) * plotW,
    y: (v) => PAD.top + plotH - (v / yMax) * plotH,
    yMax,
    xMax,
  };
}

function polyline(points: { x: number; y: number }[]): string {
  return points.map((p) => `${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ");
}

/**
 * Steps/s vs workers as an SVG: async workers as bars + line, sync envs as a
 * line, and the ideal linear scaling ray (sync/1 × workers) dashed until it
 * clips out of the top of the plot.
 */
function chartSvg(doc: ThroughputDoc): string {
  const s = makeScales(doc);
  const baseline = doc.sync[0]?.stepsPerS ?? 0;
  const parts: string[] = [];

  // Hairline grid + y labels every 500 steps/s.
  for (let v = 0; v <= s.yMax; v += 500) {
    const y = s.y(v);
    parts.push(
      `<line class="tp-gridline" x1="${PAD.left}" y1="${y.toFixed(1)}" x2="${CHART_W - PAD.right}" y2="${y.toFixed(1)}"/>`,
      `<text class="tp-tick" x="${PAD.left - 8}" y="${(y + 3).toFixed(1)}" text-anchor="end">${fmt(v)}</text>`,
    );
  }

  // X ticks at every measured worker/env count.
  const xTicks = [
    ...new Set([...doc.sync.map((p) => p.n), ...doc.async.map((p) => p.workers)]),
  ].sort((a, b) => a - b);
  for (const w of xTicks) {
    const x = s.x(w);
    parts.push(
      `<text class="tp-tick" x="${x.toFixed(1)}" y="${CHART_H - PAD.bottom + 16}" text-anchor="middle">${w}</text>`,
    );
  }
  parts.push(
    `<text class="tp-axis" x="${(PAD.left + CHART_W - PAD.right) / 2}" y="${CHART_H - 6}" text-anchor="middle">workers / envs</text>`,
    `<text class="tp-axis" x="14" y="${(PAD.top + CHART_H - PAD.bottom) / 2}" text-anchor="middle" transform="rotate(-90 14 ${(PAD.top + CHART_H - PAD.bottom) / 2})">steps/s</text>`,
  );

  // Ideal linear ray from origin, slope = sync/1, clipped at the chart top.
  if (baseline > 0) {
    const clipW = Math.min(s.xMax, s.yMax / baseline);
    parts.push(
      `<line class="tp-ideal" x1="${s.x(0).toFixed(1)}" y1="${s.y(0).toFixed(1)}" x2="${s.x(clipW).toFixed(1)}" y2="${s.y(clipW * baseline).toFixed(1)}"/>`,
      `<text class="tp-ideal-label" x="${(s.x(clipW) + 6).toFixed(1)}" y="${(s.y(clipW * baseline) + 12).toFixed(1)}">ideal ${fmt(baseline)}×w</text>`,
    );
  }

  // Async bars, one per worker count, with the value on top.
  const barW = 22;
  for (const p of doc.async) {
    const x = s.x(p.workers) - barW / 2;
    const y = s.y(p.stepsPerS);
    const h = s.y(0) - y;
    const tracked = p.workers === doc.tracked.workers;
    parts.push(
      `<rect class="tp-bar${tracked ? " tracked" : ""}" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW}" height="${h.toFixed(1)}"/>`,
      `<text class="tp-bar-label${tracked ? " tracked" : ""}" x="${s.x(p.workers).toFixed(1)}" y="${(y - 6).toFixed(1)}" text-anchor="middle">${fmt(p.stepsPerS)}</text>`,
    );
  }

  // Async line over the bars, then the flat sync line.
  parts.push(
    `<polyline class="tp-line-async" points="${polyline(doc.async.map((p) => ({ x: s.x(p.workers), y: s.y(p.stepsPerS) })))}"/>`,
    `<polyline class="tp-line-sync" points="${polyline(doc.sync.map((p) => ({ x: s.x(p.n), y: s.y(p.stepsPerS) })))}"/>`,
  );
  for (const p of doc.sync) {
    parts.push(
      `<rect class="tp-dot-sync" x="${(s.x(p.n) - 3).toFixed(1)}" y="${(s.y(p.stepsPerS) - 3).toFixed(1)}" width="6" height="6"/>`,
    );
  }
  for (const p of doc.async) {
    parts.push(
      `<circle class="tp-dot-async" cx="${s.x(p.workers).toFixed(1)}" cy="${s.y(p.stepsPerS).toFixed(1)}" r="3.5"/>`,
    );
  }

  return `<svg class="tp-chart" viewBox="0 0 ${CHART_W} ${CHART_H}" role="img" aria-label="Environment steps per second versus worker count">${parts.join("")}</svg>`;
}

/** Scaling efficiency rows: measured async vs ideal linear (sync/1 × w). */
function efficiencyRows(doc: ThroughputDoc): string {
  const baseline = doc.sync[0]?.stepsPerS ?? 0;
  if (baseline <= 0) return "";
  return doc.async
    .map((p) => {
      const speedup = p.stepsPerS / baseline;
      const eff = speedup / p.workers;
      const tracked = p.workers === doc.tracked.workers;
      return `
        <div class="tp-eff-row${tracked ? " tracked" : ""}">
          <span class="tp-eff-w">w=${p.workers}</span>
          <span class="tp-eff-bar"><i style="width:${(Math.min(1, eff) * 100).toFixed(1)}%"></i></span>
          <span class="tp-eff-num">${(eff * 100).toFixed(0)}%</span>
          <span class="tp-eff-x">${speedup.toFixed(2)}×</span>
        </div>`;
    })
    .join("");
}

// --- panel ------------------------------------------------------------------

const STYLE_ID = "tp-panel-style";

const CSS = `
.tp { display: flex; flex-direction: column; gap: 1rem; max-width: 70rem; }
.tp-kicker { font-size: 0.62rem; letter-spacing: 0.16em; text-transform: uppercase; color: var(--dash-muted); }
.tp-hero { display: flex; align-items: baseline; gap: 0.9rem; flex-wrap: wrap; }
.tp-hero-num { font-family: var(--dash-display); font-size: clamp(2.2rem, 5vw, 3.4rem); line-height: 0.95; color: var(--dash-accent); letter-spacing: 0.02em; }
.tp-hero-unit { font-size: 0.85rem; color: var(--dash-text); }
.tp-hero-sub { font-size: 0.72rem; color: var(--dash-muted); }
.tp-grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(15rem, 19rem); gap: var(--dash-gap); align-items: stretch; }
@media (max-width: 980px) { .tp-grid { grid-template-columns: 1fr; } }
.tp-card { border: 1px solid var(--dash-line-soft); background: var(--dash-surface-2); padding: 0.8rem 0.9rem; min-width: 0; }
.tp-card h3 { margin: 0 0 0.6rem; font-size: 0.66rem; letter-spacing: 0.14em; text-transform: uppercase; color: var(--dash-muted); font-weight: 600; }
.tp-chart { display: block; width: 100%; height: auto; }
.tp-gridline { stroke: rgba(246, 244, 233, 0.1); stroke-width: 1; }
.tp-tick { fill: var(--dash-muted); font-size: 11px; font-family: var(--dash-font); }
.tp-axis { fill: var(--dash-muted); font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; font-family: var(--dash-font); }
.tp-ideal { stroke: rgba(246, 244, 233, 0.45); stroke-width: 1.5; stroke-dasharray: 5 5; }
.tp-ideal-label { fill: rgba(246, 244, 233, 0.55); font-size: 10.5px; font-family: var(--dash-font); }
.tp-bar { fill: rgba(200, 255, 61, 0.28); stroke: rgba(200, 255, 61, 0.55); stroke-width: 1; }
.tp-bar.tracked { fill: rgba(242, 210, 26, 0.42); stroke: var(--dash-accent); }
.tp-bar-label { fill: var(--dash-text); font-size: 11px; font-family: var(--dash-font); }
.tp-bar-label.tracked { fill: var(--dash-accent); }
.tp-line-async { fill: none; stroke: #c8ff3d; stroke-width: 2.5; stroke-linejoin: round; }
.tp-dot-async { fill: #c8ff3d; }
.tp-line-sync { fill: none; stroke: #6d8ecf; stroke-width: 2; stroke-linejoin: round; }
.tp-dot-sync { fill: #6d8ecf; }
.tp-legend { display: flex; gap: 1.1rem; flex-wrap: wrap; margin-top: 0.4rem; font-size: 0.66rem; color: var(--dash-muted); }
.tp-legend i { display: inline-block; width: 0.9rem; height: 3px; margin-right: 0.35rem; vertical-align: middle; }
.tp-legend .async i { background: #c8ff3d; }
.tp-legend .sync i { background: #6d8ecf; }
.tp-legend .ideal i { background: repeating-linear-gradient(90deg, rgba(246,244,233,0.55) 0 4px, transparent 4px 8px); }
.tp-eff-row { display: grid; grid-template-columns: 3.2rem 1fr 3rem 3.2rem; gap: 0.5rem; align-items: center; padding: 0.28rem 0; font-size: 0.74rem; }
.tp-eff-row.tracked .tp-eff-num, .tp-eff-row.tracked .tp-eff-w { color: var(--dash-accent); }
.tp-eff-w { color: var(--dash-muted); }
.tp-eff-bar { height: 0.55rem; background: rgba(246, 244, 233, 0.08); border: 1px solid var(--dash-line-soft); }
.tp-eff-bar i { display: block; height: 100%; background: rgba(200, 255, 61, 0.55); }
.tp-eff-row.tracked .tp-eff-bar i { background: var(--dash-accent); }
.tp-eff-num { text-align: right; }
.tp-eff-x { text-align: right; color: var(--dash-muted); }
.tp-note { margin: 0; font-size: 0.72rem; line-height: 1.55; color: #9aa7b4; }
.tp-note b { color: var(--dash-text); }
.tp-meta { margin: 0.55rem 0 0; font-size: 0.64rem; color: var(--dash-muted); line-height: 1.5; }
.tp-cli { display: flex; align-items: center; gap: 0.5rem; margin-top: 0.55rem; }
.tp-cli code { flex: 1; min-width: 0; overflow-x: auto; white-space: nowrap; padding: 0.5rem 0.6rem; font-size: 0.68rem; background: #05070a; border: 1px solid var(--dash-line-soft); color: var(--dash-text); }
.tp-copy { flex: none; padding: 0.45rem 0.7rem; font: 0.64rem/1 var(--dash-font); letter-spacing: 0.1em; text-transform: uppercase; color: var(--dash-accent); background: transparent; border: 1px solid var(--dash-accent-dim); cursor: pointer; }
.tp-copy:hover { background: rgba(242, 210, 26, 0.08); }
.tp-copy.done { color: var(--dash-good); border-color: var(--dash-good); }
.tp-status { padding: 1.4rem 0; font-size: 0.74rem; color: var(--dash-muted); }
.tp-status button { margin-left: 0.6rem; padding: 0.3rem 0.6rem; font: 0.64rem/1 var(--dash-font); color: var(--dash-accent); background: transparent; border: 1px solid var(--dash-accent-dim); cursor: pointer; }
`;

function ensureStyles(): void {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement("style");
  style.id = STYLE_ID;
  style.textContent = CSS;
  document.head.appendChild(style);
}

function render(el: HTMLElement, doc: ThroughputDoc): void {
  const baseline = doc.sync[0]?.stepsPerS ?? 0;
  const eff =
    baseline > 0
      ? doc.tracked.stepsPerS / baseline / doc.tracked.workers
      : 0;

  el.innerHTML = `
    <section class="tp">
      <header>
        <div class="tp-kicker">Tracked regression metric — AsyncVecEnv</div>
        <div class="tp-hero">
          <span class="tp-hero-num">${fmt(doc.tracked.stepsPerS)}</span>
          <span class="tp-hero-unit">steps/s @ ${doc.tracked.workers} workers</span>
          <span class="tp-hero-sub">${doc.tracked.speedupVsSync1.toFixed(1)}× sync/1 · ${(eff * 100).toFixed(0)}% of ideal linear · ${esc(doc.meta.host)}</span>
        </div>
      </header>

      <div class="tp-grid">
        <figure class="tp-card" style="margin:0">
          <h3>Steps/s vs workers</h3>
          ${chartSvg(doc)}
          <div class="tp-legend">
            <span class="async"><i></i>AsyncVecEnv (workers)</span>
            <span class="sync"><i></i>SyncVecEnv (n envs)</span>
            <span class="ideal"><i></i>ideal linear = sync/1 × workers</span>
          </div>
        </figure>

        <aside class="tp-card">
          <h3>Scaling efficiency vs ideal</h3>
          ${efficiencyRows(doc)}
          <p class="tp-meta">${esc(doc.meta.conditions)}. ${esc(doc.meta.control)}.</p>
        </aside>
      </div>

      <div class="tp-card">
        <h3>Waiver &amp; projection</h3>
        <p class="tp-note"><b>Waiver:</b> ${esc(doc.waiver)}</p>
        <p class="tp-note" style="margin-top:0.4rem"><b>Projection:</b> ${esc(doc.projection)}</p>
      </div>

      <div class="tp-card">
        <h3>Re-run the benchmark</h3>
        <p class="tp-note">
          The control room has no bench endpoint (it owns runs, live and drive),
          so regenerate these numbers from a terminal at the repo root and paste
          them into <b>public/dashboard/throughput.json</b> (and the README's
          Measured table — every claim is measured).
        </p>
        <div class="tp-cli">
          <code>${esc(RERUN_CMD)}</code>
          <button type="button" class="tp-copy" data-copy="${esc(RERUN_CMD)}">Copy</button>
        </div>
        <div class="tp-cli">
          <code>${esc(SCALE_CMD)}</code>
          <button type="button" class="tp-copy" data-copy="${esc(SCALE_CMD)}">Copy</button>
        </div>
        <p class="tp-meta">Source: ${esc(doc.meta.source)} · seed data ships in ${esc("dashboard/throughput.json")}</p>
      </div>
    </section>
  `;

  for (const btn of el.querySelectorAll<HTMLButtonElement>(".tp-copy")) {
    btn.addEventListener("click", () => {
      const text = btn.dataset.copy ?? "";
      void copyText(text).then((ok) => {
        btn.textContent = ok ? "Copied" : "Copy failed";
        btn.classList.toggle("done", ok);
        window.setTimeout(() => {
          btn.textContent = "Copy";
          btn.classList.remove("done");
        }, 1600);
      });
    });
  }
}

/** Mount the THROUGHPUT panel (section id `throughput`). */
export function mountThroughput(
  el: HTMLElement,
  _ctx: PanelContext,
): () => void {
  ensureStyles();
  el.innerHTML = `<div class="tp-status">Loading throughput measurements…</div>`;

  const aborter = new AbortController();

  const load = async (): Promise<void> => {
    try {
      const res = await fetch(DATA_URL, { signal: aborter.signal });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const doc = (await res.json()) as ThroughputDoc;
      if (!aborter.signal.aborted) render(el, doc);
    } catch (err) {
      if (aborter.signal.aborted) return;
      el.innerHTML = `<div class="tp-status">Failed to load ${esc(DATA_URL)} — ${esc(String(err))}<button type="button">Retry</button></div>`;
      el.querySelector("button")?.addEventListener("click", () => void load());
    }
  };
  void load();

  return () => {
    aborter.abort();
  };
}

registerPanel("throughput", mountThroughput);
