import * as THREE from './vendor/three.module.js';
import {makeTrack,Trainer,newCar,tickCar,rng,clamp,DT,POPULATION,readDriver} from './engine.mjs';
const $=id=>document.getElementById(id);
let track=makeTrack(),trainer=new Trainer(track),running=false,mode='train',replayCar=null,cameraMode='orbit',speedMultiplier=20,simulationDebt=0;
let angle=.68,pitch=.83,zoom=440,drag=null,lastTime=0,lastUI=0,world,carModels=[],lastGeneration=1;
const viewport=$('viewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#293627');scene.fog=new THREE.Fog('#293627',550,1100);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.prepend(renderer.domElement);$('loading').remove();}catch(e){$('loading').textContent='This simulation needs WebGL. Please enable hardware acceleration and reload.';throw e;}
const camera=new THREE.PerspectiveCamera(43,1,.2,1400);const sun=new THREE.DirectionalLight('#fff5d4',3.2);sun.position.set(-100,220,60);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-220,right:220,top:220,bottom:-220,near:1,far:500});sun.shadow.normalBias=1;scene.add(sun);scene.add(new THREE.HemisphereLight('#dce7c7','#393929',2));
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:1,...extra});
const grass=mat('#ffffff',{vertexColors:true,flatShading:true}),roadMat=mat('#b5a071'),edgeMat=mat('#827c52'),trunkMat=mat('#4e5037'),treeMats=['#334e30','#3b5632','#435c34'].map(c=>mat(c)),darkMat=mat('#151d18'),glassMat=mat('#243c39',{roughness:.4}),whiteMat=mat('#ecefd6');
function mesh(geo,material,x=0,y=0,z=0,parent=world){let o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function ribbon(width,lift,material){const v=[],idx=[];for(let i=0;i<=track.n;i++){let p=track.points[i%track.n];for(const side of [-1,1]){let x=p.x-Math.sin(p.angle)*width*side/2,z=p.z+Math.cos(p.angle)*width*side/2;v.push(x,track.height(x,z)+lift,z);}if(i<track.n){let j=i*2;idx.push(j,j+1,j+2,j+1,j+3,j+2);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();let m=mesh(g,material);m.material.side=THREE.DoubleSide;return m;}
function buildWorld(){if(world){scene.remove(world);world.traverse(o=>{if(o.geometry)o.geometry.dispose();});}world=new THREE.Group();scene.add(world);carModels=[];
 const geometry=new THREE.PlaneGeometry(405,348,90,78);geometry.rotateX(-Math.PI/2);const pos=geometry.attributes.position,colors=[];const random=rng(track.seed+300);for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i);pos.setY(i,track.height(x,z)-.06);const c=new THREE.Color().setHSL(.235+(random()-.5)*.025,.16+random()*.09,.27+random()*.08+track.height(x,z)*.0015);colors.push(c.r,c.g,c.b);}geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();mesh(geometry,grass);ribbon(16,.09,edgeMat);ribbon(12,.16,roadMat);
 // Exposed sides make the uneven landscape readable as a terrain tile.
 const rim=[];for(let x=-202.5;x<=202.5;x+=4.5)rim.push([x,-174]);for(let z=-174;z<=174;z+=4.35)rim.push([202.5,z]);for(let x=202.5;x>=-202.5;x-=4.5)rim.push([x,174]);for(let z=174;z>=-174;z-=4.35)rim.push([-202.5,z]);let vertices=[];for(let i=0;i<rim.length;i++){let p=rim[i],q=rim[(i+1)%rim.length];vertices.push(p[0],track.height(...p),p[1],q[0],track.height(...q),q[1],p[0],-28,p[1],q[0],track.height(...q),q[1],q[0],-28,q[1],p[0],-28,p[1]);}let sides=new THREE.BufferGeometry();sides.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));sides.computeVertexNormals();mesh(sides,mat('#3c4330',{side:THREE.DoubleSide}));
 const base=mesh(new THREE.PlaneGeometry(2000,2000),mat('#293627'),0,-29,0);base.rotation.x=-Math.PI/2;
 for(let i=0;i<205;i++){let x=(random()-.5)*385,z=(random()-.5)*327;let distance=Math.min(...track.points.filter((_,i)=>i%5===0).map(p=>Math.hypot(x-p.x,z-p.z)));if(distance<20)continue;let h=5+random()*10,y=track.height(x,z);mesh(new THREE.CylinderGeometry(.5,.8,h*.4,5),trunkMat,x,y+h*.2,z);mesh(new THREE.ConeGeometry(h*.3,h*.85,5),treeMats[i%3],x,y+h*.65,z);mesh(new THREE.ConeGeometry(h*.23,h*.68,5),treeMats[(i+1)%3],x,y+h*.95,z);}
 for(let i=0;i<track.n;i+=12){let p=track.points[i];for(let s of [-1,1]){let x=p.x-Math.sin(p.angle)*8*s,z=p.z+Math.cos(p.angle)*8*s;mesh(new THREE.CylinderGeometry(.16,.16,1.8,5),i%24===0?whiteMat:mat('#9cac7f'),x,track.height(x,z)+.9,z);}}
 const start=track.points[0];const gate=new THREE.Group();gate.position.set(start.x,start.y,start.z);gate.rotation.y=-start.angle;world.add(gate);for(let side of [-1,1])mesh(new THREE.BoxGeometry(.6,7,.6),darkMat,0,3.5,side*7.5,gate);mesh(new THREE.BoxGeometry(.7,1.5,16),darkMat,0,7,0,gate);for(let i=0;i<16;i++)mesh(new THREE.BoxGeometry(.73,.5,.5),i%2?darkMat:whiteMat,0,7.1,(i-7.5)*.8,gate);
 for(let row=0;row<2;row++)for(let i=0;i<12;i++){const localX=row*.8-0.4,localZ=i-5.5;let x=start.x+Math.cos(start.angle)*localX-Math.sin(start.angle)*localZ,z=start.z+Math.sin(start.angle)*localX+Math.cos(start.angle)*localZ;let tile=mesh(new THREE.PlaneGeometry(.8,1),((i+row)%2)?darkMat:whiteMat,x,track.height(x,z)+.2,z);tile.rotation.set(-Math.PI/2,0,-start.angle);}
 for(let i=0;i<POPULATION;i++){const car=new THREE.Group(),bodyMat=mat('#d6fa59');car.userData.body=bodyMat;mesh(new THREE.BoxGeometry(4.2,.85,1.85),bodyMat,0,.95,0,car);mesh(new THREE.BoxGeometry(1.95,.72,1.58),glassMat,-.2,1.68,0,car);mesh(new THREE.BoxGeometry(1.65,.15,1.64),bodyMat,-.3,2.08,0,car);mesh(new THREE.BoxGeometry(.5,.14,2.2),darkMat,-1.85,1.8,0,car);mesh(new THREE.BoxGeometry(.13,.28,1.45),whiteMat,2.13,1.02,0,car);for(let x of [-1.3,1.3])for(let z of [-1.02,1.02]){let wheel=mesh(new THREE.CylinderGeometry(.46,.46,.36,8),darkMat,x,.55,z,car);wheel.rotation.x=Math.PI/2;}car.scale.setScalar(1.1);world.add(car);carModels.push(car);}
 updateTrackInfo();drawProfile();}
function updateTrackInfo(){$('length').textContent=Math.round(track.length);$('ascent').textContent=Math.round(track.ascent);$('distance-label').textContent=Math.round(track.length)+' m';$('track-label').textContent='RIDGELINE '+track.seed;let heights=track.points.map(p=>p.y);$('elevation-span').textContent=Math.round(Math.max(...heights)-Math.min(...heights))+' m range';}
const followTarget=new THREE.Vector3();
function renderScene(){let leader=mode==='replay'?replayCar:trainer.leader;const cars=mode==='replay'?[replayCar]:trainer.population;
 carModels.forEach((o,i)=>{const c=cars[i];o.visible=!!c&&!c.dead;if(!o.visible)return;const isLeader=c===leader;o.userData.body.color.set(isLeader?'#d6fa59':'#8bada0');o.position.set(c.x,c.y+.12,c.z);let grade=track.points[c.index].grade;o.rotation.set(0,-c.heading,Math.atan(grade));o.scale.setScalar(isLeader?1.32:1);});
 if(cameraMode==='follow'&&leader){followTarget.set(leader.x,leader.y+1,leader.z);let target=new THREE.Vector3(leader.x-Math.cos(leader.heading)*32,leader.y+23,leader.z-Math.sin(leader.heading)*32);camera.position.lerp(target,.07);camera.lookAt(followTarget);}else{camera.position.set(Math.sin(angle)*Math.cos(pitch)*zoom,Math.sin(pitch)*zoom,Math.cos(angle)*Math.cos(pitch)*zoom);camera.lookAt(0,-2,0);}renderer.render(scene,camera);}
function fitCanvas(canvas){const box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);canvas.width=Math.max(1,box.width*ratio);canvas.height=Math.max(1,box.height*ratio);let ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return [ctx,box.width,box.height];}
function drawProfile(){const [ctx,w,h]=fitCanvas($('profile'));const heights=track.points.map(p=>p.y),min=Math.min(...heights)-3,max=Math.max(...heights)+3;ctx.strokeStyle='#313d2b';ctx.lineWidth=1;for(let y of [.25,.75]){ctx.beginPath();ctx.moveTo(0,h*y);ctx.lineTo(w,h*y);ctx.stroke();}ctx.beginPath();track.points.forEach((p,i)=>{const x=i/(track.n-1)*w,y=h-8-(p.y-min)/(max-min)*(h-17);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle='#bddb7c';ctx.lineWidth=1.5;ctx.stroke();ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#82994a55');grad.addColorStop(1,'#82994a03');ctx.fillStyle=grad;ctx.fill();}
function drawChart(){
 const [ctx,w,h]=fitCanvas($('chart'));ctx.strokeStyle='#303a2a';ctx.setLineDash([3,5]);for(let y of [3,h/2,h-8]){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.setLineDash([]);
 const history=trainer.history.slice(-70),laps=history.filter(p=>p.lap),isLap=laps.length>0,values=isLap?laps.map(p=>p.lap):[0,100];
 const lo=isLap?Math.floor(Math.min(...values)-2):0,hi=isLap?Math.ceil(Math.max(...values)+2):100;
 const labels=document.querySelectorAll('.chart-y span');[hi,(hi+lo)/2,lo].forEach((v,i)=>labels[i].textContent=isLap?v.toFixed(0)+'s':v+'%');
 $('curve-caption').textContent=isLap?'Fastest lap per generation · lower is better':'Best completion per generation';
 $('chart-empty').style.display=history.length?'none':'flex';if(!history.length)return;
 const points=history.map((p,i)=>({x:i/Math.max(1,history.length-1)*(w-5)+2,value:isLap?p.lap:p.completion})).filter(p=>p.value!==null);
 ctx.strokeStyle='#d6fa59';ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>{const y=h-8-(p.value-lo)/(hi-lo)*(h-12);i?ctx.lineTo(p.x,y):ctx.moveTo(p.x,y);});ctx.stroke();
 for(const p of points){ctx.beginPath();ctx.arc(p.x,h-8-(p.value-lo)/(hi-lo)*(h-12),history.length<20?2.5:1.2,0,Math.PI*2);ctx.fillStyle='#d6fa59';ctx.fill();}
 $('chart').setAttribute('aria-label',isLap?'Fastest lap time per generation in seconds':'Best track completion per generation');
 $('chart-range').textContent='GEN '+String(history[0].generation).padStart(2,'0')+' → '+String(history.at(-1).generation).padStart(2,'0');
}
function syncUI(){const c=mode==='replay'?replayCar:trainer.leader,progress=clamp(c.bestProgress/track.length*100,0,100);$('speed').textContent=Math.round(c.speed*3.6);$('generation').textContent=String(trainer.generation).padStart(3,'0');$('generation-inline').textContent=String(trainer.generation).padStart(3,'0');$('best-lap').innerHTML=trainer.bestLap?trainer.bestLap.toFixed(2)+'<small> s</small>':'—<small> s</small>';$('completion').textContent=progress.toFixed(0)+'%';$('progress-bar').style.width=progress+'%';$('throttle-bar').style.width=Math.abs(c.throttle)*100+'%';$('throttle-bar').style.background=c.throttle<0?'#f2916e':'#d6fa59';$('steer-bar').style.left=(50+c.steer*90)+'%';$('alive').textContent=mode==='replay'?1:trainer.population.filter(c=>!c.dead&&!c.finished).length;$('episode').textContent=c.time.toFixed(1)+' s';$('replay').disabled=!trainer.bestLap;$('export').disabled=!trainer.champion;$('laps-count').textContent=trainer.totalLaps+' completed laps';if(trainer.generation!==lastGeneration){lastGeneration=trainer.generation;drawChart();} }
function setState(){let replay=mode==='replay';$('start-text').textContent=running?(replay?'Pause replay':'Pause training'):(replay?'Resume replay':trainer.elapsed?'Resume training':'Start training');$('start-icon').textContent=running?'Ⅱ':'▶';$('status').textContent=running?(replay?'Replaying best lap':'Training in progress'):(trainer.elapsed?'Session paused':'Ready to train');$('view-label').textContent=replay?'BEST LAP REPLAY':'LIVE SIMULATION';}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
$('start').onclick=()=>{if(mode==='replay'&&(replayCar.finished||replayCar.dead))replayCar=newCar(track,trainer.champion.weights);running=!running;setState();};$('speed-select').onchange=e=>{speedMultiplier=+e.target.value;simulationDebt=0;};
$('elevation').oninput=e=>$('elevation-value').textContent=e.target.value+' m';
$('generate').onclick=()=>{let seed=+$('seed').value;if(!Number.isInteger(seed)||seed<1||seed>999999){toast('Choose a whole-number seed from 1 to 999999.');return;}if(seed===track.seed&&+$('elevation').value===track.elevation){seed=Math.floor(Math.random()*999998)+1;$('seed').value=seed;}const weights=trainer.champion?.weights;track=makeTrack(seed,+$('elevation').value);trainer=new Trainer(track,seed+99,weights);running=false;mode='train';$('replay').textContent='↻ Replay best';lastGeneration=0;simulationDebt=0;buildWorld();drawChart();syncUI();setState();toast(weights?'New terrain. Your best driver is ready to adapt.':'New terrain generated. Ready to train.');};
$('replay').onclick=()=>{if(mode==='replay'){mode='train';$('replay').textContent='↻ Replay best';running=false;}else if(trainer.champion?.lap){replayCar=newCar(track,trainer.champion.weights);mode='replay';running=true;$('replay').textContent='← Back to training';toast('Replaying the fastest driver at real time.');}simulationDebt=0;setState();};
$('export').onclick=()=>{if(!trainer.champion)return;const payload={format:'rally-neural-policy-v1',createdAt:new Date().toISOString(),algorithm:'elitist-neuroevolution',inputs:['heading_8m','heading_18m','heading_35m','heading_60m','lateral_offset','speed','slip','curvature','grade','load_delta','previous_steer','bias'],outputs:['steering','throttle_brake'],activation:'tanh',weights:trainer.champion.weights,track:{seed:track.seed,elevation:track.elevation},bestLapSeconds:trainer.bestLap,generation:trainer.champion.generation};let url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rally-driver-'+track.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Driver weights and track settings exported.');};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;
 if(file.size>1e6){toast('That file is too large to be a driver export.');return;}
 let data;try{data=JSON.parse(await file.text());}catch{toast('That file is not valid JSON.');return;}
 let driver;try{driver=readDriver(data);}catch(err){toast(err.message);return;}
 const weights=driver.weights,known=driver.seed!==null;
 const seed=known?driver.seed:track.seed,elevation=known?driver.elevation:track.elevation;
 track=makeTrack(seed,elevation);trainer=new Trainer(track,seed+99,weights);
 // Evaluate the imported policy once so it is the champion immediately, with a real lap time.
 const probe=newCar(track,weights);while(!probe.dead&&!probe.finished)tickCar(track,probe);
 trainer.champion={weights:[...weights],score:probe.score,trace:[],lap:probe.finished?probe.time:null,progress:probe.bestProgress,generation:0};
 if(probe.finished)trainer.bestLap=probe.time;
 running=false;mode='train';replayCar=null;simulationDebt=0;lastGeneration=0;
 $('seed').value=seed;$('elevation').value=elevation;$('elevation-value').textContent=Math.round(elevation)+' m';$('replay').textContent='↻ Replay best';
 buildWorld();drawChart();syncUI();setState();
 toast(probe.finished?'Driver imported. It laps this track in '+probe.time.toFixed(2)+' s.':known?'Driver imported, but it does not finish this track yet. Train to improve it.':'Driver imported onto the current track, where it does not finish yet.');
};
$('reset').onclick=()=>{running=false;mode='train';trainer=new Trainer(track);simulationDebt=0;lastGeneration=0;drawChart();syncUI();setState();$('replay').textContent='↻ Replay best';toast('Learning reset. A fresh population is ready.');};
for(let id of ['orbit','follow'])$(id).onclick=()=>{cameraMode=id;$(id).classList.add('selected');$(id==='orbit'?'follow':'orbit').classList.remove('selected');};
$('about').onclick=()=>$('about-dialog').showModal();$('close-about').onclick=$('got-it').onclick=()=>$('about-dialog').close();$('about-dialog').addEventListener('click',e=>{if(e.target===$('about-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
viewport.addEventListener('pointerdown',e=>{if(e.target!==renderer.domElement)return;drag=[e.clientX,e.clientY];viewport.setPointerCapture(e.pointerId);});viewport.addEventListener('pointermove',e=>{if(!drag)return;angle-=(e.clientX-drag[0])*.006;pitch=clamp(pitch+(e.clientY-drag[1])*.005,.22,1.35);drag=[e.clientX,e.clientY];cameraMode='orbit';$('orbit').classList.add('selected');$('follow').classList.remove('selected');});viewport.addEventListener('pointerup',()=>drag=null);viewport.addEventListener('pointercancel',()=>drag=null);viewport.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom+e.deltaY*.25,180,740);},{passive:false});
function resize(){let b=viewport.getBoundingClientRect();renderer.setSize(b.width,b.height);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();drawChart();drawProfile();}new ResizeObserver(resize).observe(viewport);
function frame(time){const delta=Math.min((time-lastTime)/1000,.1);lastTime=time;if(running){simulationDebt=Math.min(simulationDebt+delta*(mode==='replay'?1:speedMultiplier),2);const budget=performance.now()+13;while(simulationDebt>=DT&&performance.now()<budget){if(mode==='replay'){tickCar(track,replayCar);if(replayCar.finished||replayCar.dead){running=false;setState();toast(replayCar.finished?'Best lap complete: '+replayCar.time.toFixed(2)+' seconds.':'Replay ended.');break;}}else trainer.step();simulationDebt-=DT;}}renderScene();if(time-lastUI>100){syncUI();lastUI=time;}requestAnimationFrame(frame);}
buildWorld();resize();syncUI();requestAnimationFrame(frame);
