const $=id=>document.getElementById(id);let data=null,selected=null,busy=false,initialized=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x||0).toLocaleString(undefined,{maximumFractionDigits:0});
const terminal=x=>['completed','failed','stopped'].includes(x);
async function api(url,body){const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw Error(result.detail||'Request failed');return result;}
function error(message){$('error').hidden=!message;$('error').textContent=message||'';}
function options(){return{character:'JIGGLYPUFF',workers:+$('workers').value,cpu_level:+$('level').value,total_steps:+$('steps').value,action_frames:+$('timing').value,stage:$('stage').value,curriculum:$('curriculum').checked,checkpoint:$('checkpoint').value||null};}
async function start(mode){if(busy)return;busy=true;error('');try{const result=await api('/api/runs',{mode,...options()});selected=result.id;await refresh();}catch(e){error(e.message)}finally{busy=false}}
$('train-form').addEventListener('submit',e=>{e.preventDefault();start('train')});['evaluate','watch','benchmark'].forEach(mode=>$(mode).onclick=()=>start(mode));
['pause','resume','stop'].forEach(action=>$(action).onclick=async()=>{if(!selected)return;try{await api(`/api/runs/${selected}/${action}`,{});await refresh()}catch(e){error(e.message)}});
$('checkpoint').onchange=()=>{const checkpoint=data?.checkpoints.find(c=>c.path===$('checkpoint').value);if(checkpoint){$('timing').value=checkpoint.contract.action_frames;const level=checkpoint.curriculum?.level;if(level)$('level').value=level;}};
function draw(run){const c=$('chart'),ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#293644';ctx.lineWidth=1;for(let y=20;y<h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const points=run?.history||[];$('empty-chart').style.display=points.length?'none':'grid';if(!points.length)return;const values=points.map(p=>p.entropy),max=Math.max(...values,1)*1.1;const coords=values.map((y,i)=>[i*w/Math.max(1,values.length-1),h-15-y/max*(h-35)]);ctx.beginPath();ctx.moveTo(0,h);coords.forEach(p=>ctx.lineTo(...p));ctx.lineTo(w,h);ctx.closePath();const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,'#b4f2ce28');gradient.addColorStop(1,'#b4f2ce00');ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();coords.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle='#b4f2ce';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#8d9aab';ctx.font='10px system-ui';ctx.fillText('Policy entropy · exploration over updates',8,12);}
function render(){
const runs=data.runs;if(!selected||!runs.some(r=>r.id===selected))selected=runs.find(r=>!terminal(r.status))?.id||runs[0]?.id;
const run=runs.find(r=>r.id===selected);$('connection').textContent='● Local system connected';$('disk').textContent=`${data.disk_free_gb} GB available`;
if(!initialized){$('workers').value=data.config.workers;$('timing').value=data.config.action_frames;$('steps').value=data.config.total_steps;initialized=true}
const choice=$('checkpoint').value;$('checkpoint').innerHTML='<option value="">Fresh policy — start from scratch</option>'+data.checkpoints.filter(c=>c.contract.character==='JIGGLYPUFF'&&c.backend==='dolphin').map(c=>`<option value="${esc(c.path)}">${fmt(c.steps)} decisions · ${esc(c.sha256.slice(0,8))}</option>`).join('');$('checkpoint').value=choice;
$('run-status').textContent=(run?.status||'ready').toUpperCase();$('accepted').textContent=run?fmt(run.steps):'—';$('throughput').textContent=run?.accepted_per_second?.toFixed(1)||'—';$('updates').textContent=run?fmt(run.updates):'—';$('progress').style.width=`${Math.min(100,100*(run?.steps||0)/(run?.target_steps||1))}%`;$('run-label').textContent=run?.id||'No run selected';$('run-phase').textContent=run?.phase||'Awaiting a run';$('run-error').textContent=run?.error||'';
const active=run&&!terminal(run.status);$('pause').disabled=!active||run.mode!=='train'||run.status==='paused';$('resume').disabled=!active||run.status!=='paused';$('stop').disabled=!active;
$('evaluate').disabled=!choice;$('watch').disabled=!choice;$('benchmark').disabled=runs.some(r=>!terminal(r.status));
const slots=run?.slots||[];$('worker-count').textContent=`${slots.filter(s=>['playing','starting','resetting','recovering'].includes(s.phase)).length.toString().padStart(2,'0')} ONLINE`;
$('workers-grid').innerHTML=slots.length?slots.map(s=>{const a=s.players?.['1'],b=s.players?.['2'];return `<div class="worker"><div class="workerhead"><b>GAME ${String((s.index||0)+1).padStart(2,'0')}</b><span class="phase">${esc(s.phase||'starting')}</span></div><p>vs ${esc(s.opponent||'—')} · CPU ${s.cpu_level??'—'}</p>${a?`<div class="stocks">${'●'.repeat(Math.max(0,a.stocks))||'—'} <i>${Math.round(a.percent)}% / ${Math.round(b?.percent||0)}%</i> ${'●'.repeat(Math.max(0,b?.stocks||0))||'—'}</div>`:''}<small>${fmt(s.collected)} collected · policy ${s.policy_version??'—'}</small>${s.error?`<p>${esc(s.error)}</p>`:''}</div>`}).join(''):'<div class="blank">Each worker owns a game. One resetting worker does not stop the others.</div>';
$('matchups').innerHTML=run?.matchups?.length?run.matchups.map(m=>`<tr><td>${esc(m.opponent)}</td><td>${m.cpu??'—'}</td><td>${m.attempts}</td><td>${m.wins} / ${m.attempts}</td><td>${m.timeouts} / ${m.interruptions}</td></tr>`).join(''):'<tr><td colspan="5">No matches recorded.</td></tr>';
$('evidence-note').textContent=run?.backend==='synthetic'?'Synthetic pipeline test — these results are not Melee evidence.':run?.mode==='evaluate'?`Deterministic raw-input evaluation. All attempts count, including timeouts and failures.${run.interval?' 95% win-rate interval: '+run.interval.map(n=>(100*n).toFixed(0)+'%').join('–'):''}`:'Training outcomes show exploration, not a benchmark of playing strength.';
const bench=data.benchmarks.find(b=>b.backend==='dolphin');if(bench){let max=Math.max(1,...bench.results.map(r=>r.decisions_per_second));$('benchmark-results').innerHTML=bench.results.map(r=>`<div class="benchrow"><span>${r.workers} worker${r.workers>1?'s':''}</span><div class="benchbar"><i style="width:${r.decisions_per_second/max*100}%"></i></div><b>${r.decisions_per_second.toFixed(1)} /s</b></div>`).join('')+`<p class="hint">${esc(bench.status)}${bench.recommended_workers?' · fastest measured: '+bench.recommended_workers+' workers':''}</p>`;}
$('runs').innerHTML=runs.length?runs.map(r=>`<div class="runrow ${r.id===selected?'selected':''}" data-run="${esc(r.id)}"><div>${esc(r.mode)} <small>${esc(r.id)}</small></div><div>${esc(r.status)}<small>${esc(r.backend||'dolphin')}</small></div><div>${fmt(r.steps)}<small>trained decisions</small></div><div class="hash">${esc(r.latest?.sha256?.slice(0,16)||r.checkpoint?.sha256?.slice(0,16)||'No checkpoint yet')}<small>${r.parent?'Parent '+esc(r.parent.sha256.slice(0,12)):'Fresh origin'}</small></div><button data-select="${esc(r.id)}">Inspect ↗</button></div>`).join(''):'<div class="blank">Your runs will appear here.</div>';
document.querySelectorAll('[data-run]').forEach(el=>el.onclick=()=>{selected=el.dataset.run;render()});draw(run);
}
async function refresh(){try{data=await api('/api/state');render()}catch(e){$('connection').textContent='Connection lost';error(e.message)}}
window.addEventListener('resize',()=>data&&draw(data.runs.find(r=>r.id===selected)));refresh();setInterval(refresh,2000);
