import type { Material, MaterialId } from './types';

/** Simple readable materials palette — density relative to water ≈ 1. */
export const MATERIALS: Record<MaterialId, Material> = {
  steel: {
    id: 'steel',
    name: 'Steel plate',
    color: '#6a7a8c',
    density: 2.2,
    compliance: 0.00002,
    tensionLimit: 0.22,
    compressionLimit: 0.28,
    ductility: 0.35,
    hullSkin: true,
    canBrace: true,
  },
  keel: {
    id: 'keel',
    name: 'Keel steel',
    color: '#3d4a58',
    density: 2.9,
    compliance: 0.00001,
    tensionLimit: 0.3,
    compressionLimit: 0.4,
    ductility: 0.25,
    hullSkin: true,
    canBrace: true,
  },
  bulkhead: {
    id: 'bulkhead',
    name: 'Bulkhead',
    color: '#8a96a4',
    density: 1.85,
    compliance: 0.00003,
    tensionLimit: 0.2,
    compressionLimit: 0.25,
    ductility: 0.2,
    hullSkin: false,
    canBrace: true,
  },
  engine: {
    id: 'engine',
    name: 'Engine block',
    color: '#2a2e34',
    density: 4.2,
    compliance: 0.000005,
    tensionLimit: 0.35,
    compressionLimit: 0.5,
    ductility: 0.05,
    hullSkin: false,
    canBrace: false,
  },
  ice: {
    id: 'ice',
    name: 'Ice',
    color: '#b8d4e8',
    density: 0.92,
    compliance: 0.00008,
    tensionLimit: 0.08,
    compressionLimit: 0.12,
    ductility: 0.0,
    hullSkin: true,
    canBrace: false,
  },
  glass: {
    id: 'glass',
    name: 'Glass',
    color: '#9ec8d8',
    density: 1.4,
    compliance: 0.00004,
    tensionLimit: 0.05,
    compressionLimit: 0.08,
    ductility: 0.0,
    hullSkin: true,
    canBrace: false,
  },
  superstructure: {
    id: 'superstructure',
    name: 'Superstructure',
    color: '#c8c4b8',
    density: 1.1,
    compliance: 0.00006,
    tensionLimit: 0.12,
    compressionLimit: 0.15,
    ductility: 0.15,
    hullSkin: false,
    canBrace: false,
  },
  deck: {
    id: 'deck',
    name: 'Deck timber',
    color: '#8b6b45',
    density: 0.75,
    compliance: 0.0001,
    tensionLimit: 0.14,
    compressionLimit: 0.1,
    ductility: 0.4,
    hullSkin: false,
    canBrace: false,
  },
  wood: {
    id: 'wood',
    name: 'Wood',
    color: '#a07848',
    density: 0.65,
    compliance: 0.00012,
    tensionLimit: 0.12,
    compressionLimit: 0.1,
    ductility: 0.5,
    hullSkin: true,
    canBrace: true,
  },
  funnel: {
    id: 'funnel',
    name: 'Funnel sheet',
    color: '#4a5560',
    density: 1.2,
    compliance: 0.00015,
    tensionLimit: 0.08,
    compressionLimit: 0.1,
    ductility: 0.1,
    hullSkin: false,
    canBrace: false,
  },
  compartment: {
    id: 'compartment',
    name: 'Compartment',
    color: '#7a8894',
    density: 1.45,
    compliance: 0.00004,
    tensionLimit: 0.18,
    compressionLimit: 0.22,
    ductility: 0.2,
    hullSkin: false,
    canBrace: true,
  },
  rope: {
    id: 'rope',
    name: 'Rope',
    color: '#c4a06a',
    density: 0.4,
    compliance: 0.0005,
    tensionLimit: 0.25,
    compressionLimit: 0.02,
    ductility: 0.6,
    hullSkin: false,
    canBrace: false,
  },
};

export const MATERIAL_LIST: Material[] = Object.values(MATERIALS);

export const MATERIAL_INDEX: MaterialId[] = [
  'steel',
  'keel',
  'bulkhead',
  'engine',
  'ice',
  'glass',
  'superstructure',
  'deck',
  'wood',
  'funnel',
  'compartment',
  'rope',
];

export function materialByIndex(i: number): Material {
  return MATERIALS[MATERIAL_INDEX[i] ?? 'steel'];
}

export function indexOfMaterial(id: MaterialId): number {
  const i = MATERIAL_INDEX.indexOf(id);
  return i >= 0 ? i : 0;
}
